name: Build APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Decode release keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > my-upload-key.jks

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '9.3.1'

      - name: Build Release APK
        env:
          KEYSTORE_PATH: ${{ github.workspace }}/my-upload-key.jks
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: gradle assembleRelease

      - name: Rename APK
        run: cp app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/qrcode-scanner-siddhartha.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: qrcode-scanner-siddhartha
          path: app/build/outputs/apk/release/qrcode-scanner-siddhartha.apk
